### Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
xls = pd.ExcelFile('Georgian College AI Modelling Data Dictionary (2023.01.25 IK).xlsx')
data_dict = pd.read_excel(xls, 'Data Dictionary')
df = pd.read_excel(xls, 'ADRS Data')

In [3]:
df.head()

,CallNum,CallHour,PickupTown,Utm,OverallProblem,DestinationLocationName,DestinationCity,NotifyUtm,NotifyLowerTierDescription,DispatchedPriority,...,Day,Week,Quarter,Dispatch,Chute,Resp,ONSCNE,INHOSP,TOTALT0T7,TOTALT0T13
0,15022670,6,BARRIE,6054917.0,*Primary Assessment,NaN,NaN,6024919,Springwater,4,...,9,46,4,1900-01-01 00:00:33,1900-01-01 00:01:38,NaT,NaT,NaN,NaT,1900-01-01 00:11:56
1,15022670,6,BARRIE,6054917.0,*Primary Assessment,1825 Royal Victoria RVH HO,BARRIE,6034914,Barrie,4,...,9,46,4,1900-01-01 00:03:08,1900-01-01 00:00:28,1900-01-01 00:06:59,1900-01-01 00:07:30,1900-01-01 01:20:48,1900-01-01 01:43:54,NaN
2,15022685,7,MIDLAND,5874954.0,11 Chest Pain/Heart Problem,1844 Georgian Bay General Site 1 HO,MIDLAND,5894953,Midland,4,...,9,46,4,1900-01-01 00:01:59,1900-01-01 00:00:02,1900-01-01 00:04:33,1900-01-01 00:19:01,1900-01-01 00:32:51,1900-01-01 01:02:15,NaN
3,15022688,7,TAY,5914945.0,24A MVC-AutomobileEnclSeat_pa,1844 Georgian Bay General Site 1 HO,MIDLAND,5894953,Midland,4,...,9,46,4,1900-01-01 00:00:20,1900-01-01 00:00:53,1900-01-01 00:09:13,1900-01-01 00:19:27,1900-01-01 00:56:56,1900-01-01 01:38:21,NaN
4,15022688,7,TAY,5914945.0,24A MVC-AutomobileEnclSeat_pa,1844 Georgian Bay General Site 1 HO,MIDLAND,6074951,Severn,4,...,9,46,4,1900-01-01 00:03:07,1900-01-01 00:01:08,1900-01-01 00:16:17,1900-01-01 00:20:02,1900-01-01 00:34:04,1900-01-01 01:25:17,NaN

In [4]:
# Get count duplicates single column using dataframe.pivot_table()
df2 = df.pivot_table(index = ['CallNum'], aggfunc ='size')
df2.head()

CallNum
32159    1
32631    1
32751    1
36237    1
42614    1
dtype: int64

In [5]:
df2 = pd.DataFrame(df2)

In [6]:
df2['CallNum'] = df2.index

In [7]:
df2.rename( columns={0:'No. of Resources Assigned'}, inplace=True )

In [8]:
df2.columns

Index(['No. of Resources Assigned', 'CallNum'], dtype='object')

In [9]:
df2.head()

         No. of Resources Assigned  CallNum
CallNum
32159                            1    32159
32631                            1    32631
32751                            1    32751
36237                            1    36237
42614                            1    42614

In [10]:
df2.reset_index(drop=True, inplace=True)

In [11]:
df2.head()

   No. of Resources Assigned  CallNum
0                          1    32159
1                          1    32631
2                          1    32751
3                          1    36237
4                          1    42614

In [12]:
df2[df2['No. of Resources Assigned'] >= 2]

        No. of Resources Assigned   CallNum
154                             2   1604257
160                             3   2248585
192                             2   4455136
194                             2   4456276
200                             2   4463113
...                           ...       ...
448202                          2  22677849
448205                          2  22681448
448206                          2  22681458
448208                          2  22681687
448215                          2  22700878

[89342 rows x 2 columns]

In [13]:
df2.head()

   No. of Resources Assigned  CallNum
0                          1    32159
1                          1    32631
2                          1    32751
3                          1    36237
4                          1    42614

In [14]:
df = df[['CallNum','T4_ArrivedScene']]

In [15]:
df.head()

    CallNum     T4_ArrivedScene
0  15022670                 NaT
1  15022670 2015-11-09 06:22:11
2  15022685 2015-11-09 07:41:37
3  15022688 2015-11-09 08:07:11
4  15022688 2015-11-09 08:17:02

In [16]:
df2 = df2[:20]

In [17]:
#df = df.reset_index()  # make sure indexes pair with number of rows
#df2 = df2.reset_index()

count = 0

df2['Required Resources'] = np.nan


for index, row in df.iterrows():
    count = 0
    for index2, row2 in df2.iterrows():
        if (int(row['CallNum']) == int(row2['CallNum'])) and str(row['T4_ArrivedScene']) != 'NaT':
            count += 1
            
    df2.loc[df2['CallNum'] == int(row['CallNum']), 'Required Resources'] = count
            
            #print(row['CallNum'],row2['CallNum'])
            
#print(count)
    #print(row['CallNum'], row['T4_ArrivedScene'])

In [18]:
df2.head()

   No. of Resources Assigned  CallNum  Required Resources
0                          1    32159                 1.0
1                          1    32631                 1.0
2                          1    32751                 1.0
3                          1    36237                 1.0
4                          1    42614                 1.0

In [19]:
print(df2)

    No. of Resources Assigned  CallNum  Required Resources
0                           1    32159                 1.0
1                           1    32631                 1.0
2                           1    32751                 1.0
3                           1    36237                 1.0
4                           1    42614                 1.0
5                           1    42752                 1.0
6                           1    43807                 1.0
7                           1    44736                 0.0
8                           1    45353                 1.0
9                           1    46337                 1.0
10                          1    47401                 1.0
11                          1    47679                 1.0
12                          1    48616                 1.0
13                          1    49339                 1.0
14                          1    49947                 1.0
15                          1    50064                 1.0
16                          1    65127                 1.0
17                          1    66092                 1.0
18                          1    66116                 1.0
19                          1    66351                 1.0